# Generated by Django 5.1 on 2024-09-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing')], default='ongoing', max_length=10),
        ),
    ]
