# Generated by Django 5.1 on 2024-09-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aboutsection_aboutimage_delete_about_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutimage',
            name='about_section',
        ),
    ]
